drop database pfe;
create database pfe;
use pfe;
create table Admin(login varchar(50) primary key, pwd varchar(50));
create table Utilisateur(immatricule int primary key auto_increment, login varchar(50), pwd varchar(50), nom varchar(50), prenom varchar(50), email varchar(50), fonction varchar(50), sexe varchar(50));
create table EB(num  int primary key auto_increment, objet varchar(50), agence varchar(50), observation varchar(50), prog_nonprog int, classe varchar(50), caution double, estimation double, dateEB date, modePassation varchar(50), dateValidation date, validerPar varchar(50), numUtilisateur int, numQualification int);
create table Operation(code int primary key, agence varchar(50), DA longblob, imputation varchar(50), natureProjet varchar(50), operation varchar(50), programme varchar(50), situation varchar(50), superficie varchar(50), typeProjet varchar(50), numEB int);
create table Piece(num int primary key auto_increment, libelle varchar(50), piece longblob, numEB int);
create table Qualification(num int primary key auto_increment, qualification varchar(50), numSecteur int);
create table Secteur(num int primary key auto_increment, secteur varchar(50));
create table AO(num varchar(50) primary key, etat varchar(50), dateOuverturePlis date, heureOuverturePlis timestamp, datePublicationPortail date, dateEntreDM date, dateAchevementTravauxCommission date, avis longblob, numEB int, numLettreCommission int);
create table Marche(num varchar(50) primary key, numCommande varchar(50), marche varchar(50), numAO varchar(50));
create table Journal(num int primary key, numEnvoie int, format varchar(50), fournisseur varchar(50), dateEnvoie date, datePublication date, lettreJournal longblob, numAo varchar(50));
create table Facture(num int primary key auto_increment, dateFacture date, montant double, numJournal int);
create table LettreCommission(num int primary key auto_increment, numEnvoie int, dateEnvoie date, destinataire varchar(50), lettreCommission longblob);
alter table EB add foreign key (numUtilisateur) references Utilisateur(immatricule);
alter table Operation add foreign key (numEB) references EB(num);
alter table Piece add foreign key (numEB) references EB(num);
alter table EB add foreign key (numQualification) references Qualification(num);
alter table Qualification add foreign key (numSecteur) references Secteur(num);
alter table AO add foreign key (numEB) references EB(num);
alter table Marche add foreign key (numAO) references AO(num);
alter table AO add foreign key (numLettreCommission) references LettreCommission(num);
alter table Journal add foreign key (numAO) references AO(num);
alter table Facture add foreign key (numJournal) references Journal(num);